#Config file for problem definitions
step_size: 15  #15, 30
tstep_per_day: 96
window_size: 96 #in this case is the same as tsteps_perday
num_days: 1 #days to be used somewhere
time_units: mins

#dataset
dataset_unit: kwh #kw or kwh
dataset_file: 'dataset_gecad_clean.csv'

# data_info:
#   data_file: 'Dataset_gecad_changed.xlsx'
#   data_proc_cls: GecadDataProcessor

#Data Range
t_init: 0
t_end: 35136 # length of gecad data

# t_init: 0
# t_end: 192 # length of gecad data

# t_init: 1056
# t_end: 1248

# t_init: 34656
# t_end: 34848

# t_init: 32448
# t_end: 32640

# t_init: 15648
# t_end: 15840


allowed_init_config:
  clean_pv_data: True
  day_select: False
  pv_threshold: 4.0



#environment configs
env_info: 'training environment'
done_condition: 'mode_window'
init_condition: 'mode_window'

# seed: 1024
normalization: True

#PV
pv_factor: 1


#forecasting
t_ahead_hours: 2
